DROP TABLE IF EXISTS images;

CREATE TABLE images (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  author VARCHAR(50) DEFAULT NULL,
  uploaded TIMESTAMP NOT NULL,
  filename VARCHAR(50) NOT NULL,
  image BLOB(10240K) NOT NULL,
  description VARCHAR(500) DEFAULT NULL
);
